# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Bugzilla
version:      0.6
version_from: Bugzilla.pm
installdirs:  site
requires:
    Carp:                          0
    Class::MethodMaker:            1.08
    WWW::Mechanize:                0.4

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
